
modLoader="javafml"
loaderVersion="[43,)"
license="Pineapple"
[[mods]]
modId="chunk_export"
version="${file.jarVersion}"
displayName="Chunk Export"
logoFile=""
credits="Someoneice"
authors="Someoneice"
description='''
'''
[[dependencies.chunk_export]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chunk_export]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"